config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get 'tags/:tag', to: 'static_pages#home', as: :tag
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      if params[:tag]
        @micropost = current_user.microposts.build
        @feed_items = current_user.feed.paginate(page: params[:page]).tagged_with(params[:tag])
      else
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.haml
- provide(:title, "Home")

- if logged_in?
  %div.row
    %aside.col-md-4
      %section.user_info
        =render 'shared/user_info'
      %section.stats
        =render 'shared/stats'
      %section.micropost_form
        =render 'shared/micropost_form'
      %section.tags_cloud
        Tags:
        %br
        -tag_cloud Micropost.tag_counts, %w[s m l] do |tag, css_class|
          =link_to tag.name, tag_path(tag.name), class: css_class


    %div.col-md-8
      %h3 Micropost Feed
      = render 'shared/feed'

- else
  %div(class="center jumbotron")
    %h1
      Welcome to the Sample App
    %h2
      This is the home page for the
      %a{href: "http://www.railstutorial.org/"}
        Ruby on Rails Tutorial
      sample application.
    = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"

  = link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/'