config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get 'tags/:tag', to: 'static_pages#home', as: :tag
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments
  acts_as_taggable
  acts_as_taggable_on :tags

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size



  private

  def picture_size
    if picture.size > 2.megabytes
      errors.add(:picture, "should be less than 5 MB")
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Post created"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def show
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments.paginate(page: params[:page])
    @comment = @micropost.comments.build if logged_in?
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture, :tag_list)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment_form.html.haml
= form_for(@comment) do |f|
  =hidden_field_tag :micropost_id, params[:id]
  =render 'shared/error_messages', object: f.object
  %div.field
    =f.text_area :content, placeholder: "Add new comment..."
  =f.submit "Add", class: "btn btn-primary"

app/views/microposts/_micropost.html.haml
%li{id: "micropost-#{micropost.id}"}
  =link_to gravatar_for(micropost.user, size: 50), micropost.user
  %span.user
    =link_to micropost.user.name, micropost.user
  %span.content
    = link_to micropost_path(micropost.id) do
      =micropost.content
      = image_tag micropost.picture.url if micropost.picture?
  %span.tags
    Tags:
    =raw micropost.tag_list.map { |t| link_to t, tag_path(t)}.join(', ')

  %span.timestamp
    Posted
    =time_ago_in_words(micropost.created_at)
    ago
    = link_to "delete", micropost, method: :delete, data: { confirm: "Are you sure?" }

app/views/microposts/show.html.haml
%div.comments
  =link_to gravatar_for(@micropost.user, size: 50), @micropost.user
  %span.user
    =link_to user_path(@micropost.user) do
      =@micropost.user.name
  %span.content
    =@micropost.content
  %span.timestamp
    Posted:
    =time_ago_in_words(@micropost.created_at)
    ago
    = link_to "delete", @micropost, method: :delete, data: { confirm: "Are you sure?" }


%div.col-md-4
  %h4
    Add comment:
  =render 'comment_form'
%div.col-md-6
  -if@micropost.comments.any?
    %h4
      ="Comments (#{@micropost.comments.count})"
    %ol.comments
      =render @comments
    =will_paginate @comments